### ISSUE TITLE
 Cannot destructure property 'HTTP2_HEADER_CONTENT_ENCODING' of 'http2.constants' as it is undefined.

### ISSUE THREAD

**Issue by dsaintpierre** [levz0r/gmail-tester#109]
I see that this issue was filed before, but that was with a different implementation where they were able to circumvent the issue by commenting out the `require` line.

```
> Cannot destructure property 'HTTP2_HEADER_CONTENT_ENCODING' of 'http2.constants' as it is undefined.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
at Object.eval ([webpack:///./node_modules/gmail-tester/node_modules/googleapis-common/build/src/http2.js:25:7](http://localhost:53696/__/#))
    at ./node_modules/gmail-tester/node_modules/googleapis-common/build/src/http2.js (http://localhost:53696/__cypress/tests?p=cypress/e2e/1-getting-started/login.cy.ts:60765:30)
    at __webpack_require__ ([webpack:///webpack/bootstrap:19](http://localhost:53696/__/#))
    at Object.eval ([webpack:///./node_modules/gmail-tester/node_modules/googleapis-common/build/src/apirequest.js:23:11](http://localhost:53696/__/#))
    at ./node_modules/gmail-tester/node_modules/googleapis-common/build/src/apirequest.js (http://localhost:53696/__cypress/tests?p=cypress/e2e/1-getting-started/login.cy.ts:60159:30)
    at __webpack_require__ ([webpack:///webpack/bootstrap:19](http://localhost:53696/__/#))
    at ./node_modules/gmail-tester/node_modules/googleapis-common/build/src/index.js ([webpack:///./node_modules/gmail-tester/node_modules/googleapis-common/build/src/index.js:31:19](http://localhost:53696/__/#))
    at __webpack_require__ ([webpack:///webpack/bootstrap:19](http://localhost:53696/__/#))
    at ./node_modules/gmail-tester/node_modules/googleapis/build/src/apis/abusiveexperiencereport/index.js ([webpack:///./node_modules/gmail-tester/node_modules/googleapis/build/src/apis/abusiveexperiencereport/index.js:17:28](http://localhost:53696/__/#))
    at __webpack_require__ ([webpack:///webpack/bootstrap:19](http://localhost:53696/__/#))
From previous event:
    at evalScripts (http://localhost:53696/__cypress/runner/cypress_runner.js:165456:58)
    at <unknown> (http://localhost:53696/__cypress/runner/cypress_runner.js:165468:152)
From previous event:
    at runScriptsFromUrls (http://localhost:53696/__cypress/runner/cypress_runner.js:165468:136)
    at Object.runScripts (http://localhost:53696/__cypress/runner/cypress_runner.js:165483:12)
    at $Cypress.onSpecWindow (http://localhost:53696/__cypress/runner/cypress_runner.js:153515:75)
```
My implementation is in a helper file:
```
  const email = await gmail.check_inbox(
    path.resolve(__dirname, "credentials.json"),
    path.resolve(__dirname, "token.json"),
    {
      after: time,
    }
  )
```

**Comment by johnmccollum** [comment]
I had this problem, and it was caused by not setting up the task properly - requiring "gmail-tester" in the wrong place will cause that issue.

You need to make sure that it runs as a `cy.task`, since this code should run on the Node side.

For my implementation (Cypress 11), I had to do the following in cypress.config.ts:

```ts
import { defineConfig } from 'cypress';
import * as path from 'path';
import * as gmail from 'gmail-tester';

export default defineConfig({
  e2e: {
    setupNodeEvents: (on) =>
      on('task', {
        'gmail:check': async (args) => {
          const { from, to, subject } = args;
          const email = await gmail.check_inbox(
            path.resolve(__dirname, './src/e2e/credentials.json'),
            path.resolve(__dirname, './src/e2e/token.json'),
            {
              subject: subject,
              from: from,
              to: to,
              include_body: true,
              wait_time_sec: 10,
              max_wait_time_sec: 30,
            }
          );
          return email;
        },
      }),
  },
});

```

You can then call the task in a test by doing:

```ts
cy.task('gmail:check', {
  from: 'me@test.com',
  subject: 'Whatever',
}).then((email) => {
  assert.isNotNull(email, `Email was found`);
});
```

Hope that helps!

**Comment by levz0r** [comment]
This is a usage error, not a library bug. The solution is already in the comments above from @johnmccollum.

**Problem:** `gmail-tester` uses Node.js modules (`http2`, `fs`, etc.) that don't exist in the browser. If you import it directly in a Cypress test file, it runs in the browser and fails.

**Solution:** Use `cy.task()` to run gmail-tester on the Node.js side:

```ts
// cypress.config.ts - runs in Node.js ✅
import * as gmail from 'gmail-tester';

export default defineConfig({
  e2e: {
    setupNodeEvents: (on) =>
      on('task', {
        'gmail:check': async (args) => {
          return await gmail.check_inbox(
            path.resolve(__dirname, 'credentials.json'),
            path.resolve(__dirname, 'token.json'),
            args.options
          );
        },
      }),
  },
});
```

```ts
// test.cy.ts - runs in browser
cy.task('gmail:check', { options: { subject: 'Test' } });
```

See the README for complete examples.
