### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by Sbphillips19** [levz0r/gmail-tester#12]
I have followed all the directions and my credentials.json looks exactly like the one provided in the README.  Anyone know of a fix for this?

node node_modules/gmail-tester/init.js ./cypress/plugins/credentials.json ./cypress/plugins/gmail_token.json MY_EMAIL

[gmail] Checking for message from '', to: MY_EMAIL, contains '' in subject...
[gmail] Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _get_recent_email (/Users/stephenphillips/Desktop/webApp/webapp/node_modules/gmail-tester/gmail-tester.js:41:51)
    at Object.check_inbox (/Users/stephenphillips/Desktop/webApp/webapp/node_modules/gmail-tester/gmail-tester.js:111:28)
    at /Users/stephenphillips/Desktop/webApp/webapp/node_modules/gmail-tester/init.js:4:15
    at Object.<anonymous> (/Users/stephenphillips/Desktop/webApp/webapp/node_modules/gmail-tester/init.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)

**Comment by Sbphillips19** [comment]
Started working after I posted this.  I think the correct JSON was just not saved
