### ISSUE TITLE
The API returned an error: Error: User-rate limit exceeded.

### ISSUE THREAD

**Issue by ckurban** [levz0r/gmail-tester#23]
Hi 

First of all, thank you so much for creating this package... it is quite handy... I am facing below written issues and I am using version 1.1.5. I have checked the Google Mail metrics/usage and we are nowhere near the limit but after each run, we are getting this error and we have to wait 24 hours for Google to unblock my email...  This email is only used in automation in a simplistic way to check the inbox email...

```
[0-0] [gmail] Checking for message from 'xxxxxx', to: testmailt46+1579610557685@gmail.com, contains 'Your app verification link' in subject...
[0-0] The API returned an error: Error: User-rate limit exceeded.  Retry after 2020-01-21T12:57:51.196Z
[0-0] [gmail] Error: TypeError: gmail_emails is not iterable
at _get_recent_email (/Users/yyyy/node_modules/gmail-tester/gmail-tester.js:48:29)
at process._tickCallback (internal/process/next_tick.js:68:7)

Cannot read property 'body' of undefined

```

Any help appreciated ...

**Comment by levz0r** [comment]
Hi Charlie,
Thanks!
We've never encountered this issue before... It could also be somehow related to https://github.com/levz0r/gmail-tester/issues/9. Maybe worth contacting google support? I'm not sure though...

**Comment by levz0r** [comment]
I'm going to close this issue and reopen #9.
