### ISSUE TITLE
Issue - script times out when connecting

### ISSUE THREAD

**Issue by Jacek-fstack** [levz0r/gmail-tester#27]
Does anyone have any idea why my script init.js could be timing out when connecting to gmail?
I have the credentials file, I followed all of the instructions. And after a few tries I am now getting the connection refused.
Any ideas what could be missing?
However after running the script it looks like this:
```node init.js client_secret_551825224117-b6jdrtk3e6bnin4rja7ca2luk70ar6ua.apps.googleusercontent.com.json token.json jacektestingacc@gmail.com
[gmail] Checking for message from '', to: jacektestingacc@gmail.com, contains '' in subject...
Authorize this app by visiting this url: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.readonly&response_type=code&client_id=551825224117-b6jdrtk3e6bnin4rja7ca2luk70ar6ua.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
Enter the code from that page here: 4/wQHsvgRmZNLmhgVb82egfVucO3cxNTnaTxZw1s9gpBH9Ol7xCvG2C7A
[gmail] Error: TypeError: gmail_emails is not iterable
    at _get_recent_email (/Users/jacek/Desktop/Cypress/node_modules/gmail-tester/gmail-tester.js:48:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async __check_inbox (/Users/jacek/Desktop/Cypress/node_modules/gmail-tester/gmail-tester.js:107:22)
    at async /Users/jacek/Desktop/Cypress/node_modules/gmail-tester/init.js:4:3
(node:80110) UnhandledPromiseRejectionWarning: TypeError: gmail_emails is not iterable
    at _get_recent_email (/Users/jacek/Desktop/Cypress/node_modules/gmail-tester/gmail-tester.js:48:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async __check_inbox (/Users/jacek/Desktop/Cypress/node_modules/gmail-tester/gmail-tester.js:107:22)
    at async /Users/jacek/Desktop/Cypress/node_modules/gmail-tester/init.js:4:3
(node:80110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:80110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by sampok** [comment]
Getting the same above error with v1.2.4. It hangs for ~60 sec and then:
`[gmail] Error: TypeError: gmail_emails is not iterable, at _get_recent_email`.

**Comment by Jacek-fstack** [comment]
It was timing out because the mail box had a lot of mails [800++] now it works.

**Comment by levz0r** [comment]
> It was timing out because the mail box had a lot of mails [800++] now it works.

Good catch!
Can you tell what your filters were? I am trying to understand wether the script timed out because it tried to fetch too many mails...

**Comment by Jacek-fstack** [comment]
Well it was during using the init.js, so everything there was default : )

**Comment by levz0r** [comment]
Oh right :)
