### ISSUE TITLE
Error with Cypress when check_inbox doesn't return mail

### ISSUE THREAD

**Issue by maraispierre** [levz0r/gmail-tester#38]
Hi,

When I use gmail-tester with cypress and I receive an email, test is OK.

But when I don't receive email, cypress throw an error : 

**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `/home/pierre/Documents/core/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js` or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile` to `.ts`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** /home/pierre/Documents/core/cypress/plugins/index.js:28
      return await gmail.check_inbox(
      ^^^^^^

SyntaxError: Unexpected token 'return'
    at Module._compile (internal/modules/cjs/loader.js:896:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/home/pierre/.cache/Cypress/4.9.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:208:15)
    at Object.<anonymous> (/home/pierre/.cache/Cypress/4.9.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:6:25)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)

**Stack trace:**
```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/home/pierre/Documents/core/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js` or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile` to `.ts`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/home/pierre/.cache/Cypress/4.9.0/Cypress/resources/app/packages/server/lib/errors.js:946:15)
    at EventEmitter.<anonymous> (/home/pierre/.cache/Cypress/4.9.0/Cypress/resources/app/packages/server/lib/plugins/index.js:121:21)
    at EventEmitter.emit (events.js:210:5)
    at ChildProcess.<anonymous> (/home/pierre/.cache/Cypress/4.9.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

My code is : 

**plugins/index.js**

```
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('task', {
    'gmail:check': async args => {
      const { from, to, subject } = args;
      return await gmail.check_inbox(
        path.resolve(__dirname, 'credentials.json'), // credentials.json is inside plugins/ directory.
        path.resolve(__dirname, 'gmail_token.json'), // gmail_token.json is inside plugins/ directory.
        subject,
        from,
        to,
        10,                                          // Poll interval (in seconds)
        30                                           // Maximum poll interval (in seconds). If reached, return null, indicating the completion of the task().
      )
    }
  })
}
```

**spec.js**

```
 it.only('should send an orderlight by mail', () => {
    cy.getOrderId(nameClientStorage).then(
      (orderId) => {
        cy.visit('backoffice/orderlights/'+ orderId +'/sendOrderLight')
        cy.get('[data-cy="button-send-mail"]').click({force: true})
        cy
          .task('gmail:check', {
            from: 'test@test.com',
            to: nameClientStorage,
          })
          .then(email => {
            assert.isNotNull(email, 'Email was not found')
          });
      }
    )
  })
```

**Comment by levz0r** [comment]
Hi,

I tried to reproduce the issue, but it works on my end, as seen here:

![image](https://user-images.githubusercontent.com/4564386/87202111-95498700-c308-11ea-861a-ce2b842b3ef7.png)

Could you try running the provided example?

**Comment by maraispierre** [comment]
Hi, 

I don't use 'gmail:get-messages' but 'gmail:check'. Maybe problem come from this command.

**Comment by levz0r** [comment]
Hello. Sorry for the delay.

I've added a new test spec to demonstrate how to use `check_inbox()`. Basically, when email is not found, `check_inbox()` will return `null`.

The error you had previously (The plugins file is missing or invalid), might be because of wrong project structure. Please take a look at the https://github.com/levz0r/gmail-tester/tree/master/examples/cypress directories structure.

Please let me know if the issue remains after this update.
