### ISSUE TITLE
Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by Nadya913** [levz0r/gmail-tester#5]
I have error for using gmail tester in CI.  What is the correct way how to use it in CI ? 

I run it locally (node <node_modules>/gmail-tester/init.js <path-to-credentials.json> <path-to-token.json> <target-email>) and the generated token, I put credensials.json and token in plugin folder in cypress docker , but got the error:

[gmail] Error: SyntaxError: Unexpected token T in JSON at position 0

    at JSON.parse (<anonymous>)

    at _get_recent_email (/e2e/node_modules/gmail-tester/gmail-tester.js:15:51)

    at Object.get_messages (/e2e/node_modules/gmail-tester/gmail-tester.js:120:26)

    at gmail:get-messages (/e2e/cypress/plugins/index.js:49:36)

    at invoke (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/lib/plugins/child/task.js:37:14)

    at /root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/lib/plugins/util.js:48:16

    at tryCatcher (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)

    at Function.Promise.attempt.Promise.try (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)

    at Object.wrapChildPromise (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/lib/plugins/util.js:47:28)

    at Object.wrap (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/lib/plugins/child/task.js:43:8)

    at execute (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:86:12)

    at EventEmitter.ipc.on (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:136:5)

    at emitThree (events.js:136:13)

    at EventEmitter.emit (events.js:217:7)

    at process.<anonymous> (/root/.cache/Cypress/3.4.0/Cypress/resources/app/packages/server/lib/plugins/util.js:25:29)

    at emitTwo (events.js:126:13)

**Comment by Nadya913** [comment]
Not correct credentials file was copied
