### ISSUE TITLE
Error during test run

### ISSUE THREAD

**Issue by dkoudrinhc** [levz0r/gmail-tester#72]
I've tried following the installation/setup instructions down to the letter but when I run my test case on my macbook:
I get the following error:
Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:712:16)
    at Object.send (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:32:25)
    at /Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:161:17
    at /Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:85:14
    at Promise.cancellationExecute [as _execute] (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/debuggability.js:406:9)
    at Promise._resolveFromExecutor (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:103:10)
    at Object.wrapParentPromise (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:63:12)
    at Object._get:task:body (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:146:23)
    at Object.execute (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:231:33)
    at /Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/task.js:53:22
    at tryCatcher (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dmitrikoudrin/Library/Caches/Cypress/8.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:462:21)

Is anyone able to provide any help or insights on this?

**Comment by dkoudrinhc** [comment]
Solved.

**Comment by aschuermann-at-neusta** [comment]
Solved how?
Is this a duplicate of https://github.com/levz0r/gmail-tester/issues/66?

**Comment by dkoudrinhc** [comment]
Had something wrong in the google console. There's certain settings you have to get exactly right like having a user. You also have to have your redirect uri empty otherwise it falls over.
